# This workflow always runs so we can test the action in pr.yml
# This workflow targets environment foo just like pr.yml
name: deploy-foo-two
on:
  pull_request:
    branches: [main]
jobs:
  deploy-foo-two:
    environment: foo
    runs-on: ubuntu-latest
    steps:
      # sleep to force this workflow to run longer than pr.yml so the action queues
      - shell: pwsh
        run: Start-Sleep -s 60
